---
# environment: "development"
server:
  address: "0.0.0.0:3000"
  timeout: 10  # in seconds
  shutdown: 30  # in seconds
log:
  level: "debug"  # trace, debug, info, warn, error, fatal, panic
minio:
  searchTimeout: 20  # [s]  Maximum time to wait while setting up individual minio instance
